In [28]:
import numpy as np
# np.set_printoptions(precision=3)
np.set_printoptions(suppress=True) #dont use scientific notation to print num

In [61]:

# THE POOLING FUNCTION
def pool2d(matrix, pool_size, fn):
    matrix_width, matrix_height = matrix.shape
    pool_width, pool_height = pool_size

    result_width, result_height = matrix_width//pool_width, matrix_height//pool_height
    result = np.zeros((result_width, result_height))
    for i in range(result_width):
        for j in range(result_height):
            result[i,j] = fn(matrix[i*pool_height:(i+1)*pool_height, j*pool_width:(j+1)*pool_width])
    return result


In [64]:
rand_matrix = np.random.random((6,6))*200
rand_matrix = np.vectorize(int)(rand_matrix)
print('initial matrix: ')
print(rand_matrix)

print('max pooled matrix: ')
print(pool2d(rand_matrix, (2,2), np.max))
print('avg pooled matrix: ')
print(pool2d(rand_matrix, (2,2), np.average))

initial matrix: 
[[148  68 127 175  90  33]
 [101 127  25 177 131 129]
 [ 90  48 129  64  52  34]
 [173 173 195  24 177 105]
 [ 83 108  99 184  56 127]
 [100   3 111 110 100   1]]
max pooled matrix: 
[[148. 177. 131.]
 [173. 195. 177.]
 [108. 184. 127.]]
avg pooled matrix: 
[[111.   126.    95.75]
 [121.   103.    92.  ]
 [ 73.5  126.    71.  ]]
