In [65]:
import numpy as np
# np.set_printoptions(precision=3)
np.set_printoptions(suppress=True) #dont use scientific notation to print num

In [66]:

# THE POOLING FUNCTION
def pool2d(matrix, pool_size, fn):
    matrix_width, matrix_height = matrix.shape
    pool_width, pool_height = pool_size

    result_width, result_height = matrix_width//pool_width, matrix_height//pool_height
    result = np.zeros((result_width, result_height))
    for i in range(result_width):
        for j in range(result_height):
            result[i,j] = fn(matrix[i*pool_height:(i+1)*pool_height, j*pool_width:(j+1)*pool_width])
    return result


In [67]:
rand_matrix = np.random.random((6,6))*200
rand_matrix = np.vectorize(int)(rand_matrix)
print('initial matrix: ')
print(rand_matrix)

print('max pooled matrix: ')
print(pool2d(rand_matrix, (2,2), np.max))
print('avg pooled matrix: ')
print(pool2d(rand_matrix, (2,2), np.average))

initial matrix: 
[[ 18  83 110 140 149 185]
 [ 23  18  33 197 153  22]
 [127 186 193 135  18  52]
 [130  79 145 164   8  22]
 [150  62  89 123 140 125]
 [164  44 104   3 112  87]]
max pooled matrix: 
[[ 83. 197. 185.]
 [186. 193.  52.]
 [164. 123. 140.]]
avg pooled matrix: 
[[ 35.5  120.   127.25]
 [130.5  159.25  25.  ]
 [105.    79.75 116.  ]]
